src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<slug>/', views.ProfileView.as_view(), name='profile'),
    path('user/update/', views.update_profile_info, name='edit_profile'),

]

src/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.GroupListView.as_view(), name='all_groups'),
    path('posts/in/<slug>/', views.DetailGroupView.as_view(), name='single_group'),
    path('create/', views.CreateGroup.as_view(), name='create_group'),
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave'),


]

src/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostsList.as_view(), name='all_posts'),
    path('by/<username>/', views.UserPostsList.as_view(), name='user_posts'),
    path('by/<username>/<pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('new/post/', views.PostCreateView.as_view(), name='post_create'),
    path('delete/<pk>', views.PostDeleteView.as_view(), name='delete_post'),

    ]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import SignUpView
from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('profile/', include('accounts.urls', namespace='profile')),
    path('', HomeView.as_view(), name='home'),


    path('group/', include('groups.urls', namespace="groups")),
    path('post/', include('posts.urls', namespace="posts")),
    path('search/', include('searches.urls', namespace="search")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.db.models import Q


User = get_user_model()


class GroupQuerySet(models.QuerySet):
    def search(self, query):
        lookup =(
            Q(posts__text__icontains=query)|
            Q(posts__user__username__icontains=query)|
            Q(name__icontains=query)|
            Q(slug__icontains=query)|
            Q(description__icontains=query)
        )
        return self.filter(lookup)

class GroupManager(models.Manager):

    def get_queryset(self):
        return GroupQuerySet(self.model, using=self._db)


    def search(self, query=None):
        if query is None:
            return self.get_queryset().none()
        return self.get_queryset().search(query)


class Group(models.Model):
    members = models.ManyToManyField(User, through='GroupMember')
    name = models.CharField(max_length =70, unique = True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    objects = GroupManager()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']





class GroupMember(models.Model):
    user  = models.ForeignKey(User ,related_name='user_groups' ,on_delete=models.CASCADE)
    group = models.ForeignKey(Group ,related_name='memberships' ,on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username


    class Meta:
        unique_together = ('user', 'group')

src/groups/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Group, GroupMember



class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ['name', 'description']
    model = Group
    success_url = reverse_lazy('groups:all_groups')


class DetailGroupView(generic.DetailView):
    model = Group


class GroupListView(generic.ListView):
    model = Group
    template_name = 'groups/group_list.html'



class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single_group', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug= self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user= self.request.user, group= group)
        except:
            print('user already in this grouo')
        else:
            print('joined success')
        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single_group', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(
            user = self.request.user,
            group__slug = self.kwargs.get('slug')
            ).get()
        except GroupMember.DoesNotExist:
            print('member not in this group')

        else:
            membership.delete()
            print('leaved success')

        return super().get(request, *args, **kwargs)

src/groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block title %}{% block group_title %}{% endblock %}{% endblock %}


{% block content %}

 <div class="container mt-3 mb-3">
   <div class="row">

     {% block pre_group %}{% endblock %}
     {% block group %}{% endblock %}
     {% block after_group %}{% endblock %}

   </div>
 </div>

{% endblock %}

src/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block group_title %} {{group.name }}{% endblock %}


{% block pre_group %}
<h1> {{group.name }} </h1>
<hr>
<h2>Group member: {{group.members.count }}</h2>
<hr>
<div class="content">
  {% if user in group.members.all %}
    <a href="{% url 'groups:leave' group.slug %}" class="btn btn-warning btn-lg" >
      <i class="fas fa-angle-left"></i> leave
    </a>
  {% else %}
    <a href="{% url 'groups:join' group.slug %}" class="btn btn-primary btn-lg" >
      <i class="fas fa-sign-in-alt"></i> join
    </a>
  {% endif %}

</div>
{% endblock %}

{% block group %}
<br>
<div class="col-md-8">
  {% if group.posts.count == 0 %}
    <h2>there is no Posts yet</h2>

  {% else %}

    {% for post in group.posts.all %}
      {% include "posts/_post.html" %}
    {% endfor %}

  {% endif %}
</div>
{% endblock %}

src/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load crispy_forms_tags %}
{% block group_title %} create Group{% endblock %}


{% block group %}
<form  method="post"  action="{% url 'groups:create_group' %}">
  <h2> Create New Group!</h2>
  {% csrf_token %}
  {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Login</button>
</form>




{% endblock %}

src/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% block group_title %} Group List {% endblock %}


{% block pre_group %}
<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
      <h2> Welcome Back!
        <a href="{% url 'accounts:profile' request.user.profile.PROSlug %}">@{{request.user.username}}</a>
      </h2>
      <hr>
    {% endif %}

    <h2>Groups </h2>
    <p>Welcome To the Group Page!</p>
    {% if user.is_authenticated %}
      <a href="{% url 'groups:create_group' %}" class="btn btn-primary">
        <i class="fas fa-plus-circle"></i> create new group!
      </a>
    {% endif %}
  </div>
</div>
{% endblock %}

{% block group %}

<div class="col-md-8">

  <div class="list-group">

    {% for group in group_list %}
      <a href="{% url 'groups:single_group' group.slug %}" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{group.name}}</h5>

          <small>{{group.created_at}}</small>
        </div>
        <p class="mb-1">{{group.description|safe}}</p>

        <div>
          <span class="badge">{{ group.members.count}}</span>
          member
        </div>

        <div>
          <span class="badge">{{ group.posts.count}}</span>
          posts
        </div>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock %}