src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<slug>/', views.ProfileView.as_view(), name='profile'),
    path('user/update/', views.update_profile_info, name='edit_profile'),

]

src/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.GroupListView.as_view(), name='all_groups'),
    path('posts/in/<slug>/', views.DetailGroupView.as_view(), name='single_group'),
    path('create/', views.CreateGroup.as_view(), name='create_group'),
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave'),


]

src/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostsList.as_view(), name='all_posts'),
    path('by/<username>/', views.UserPostsList.as_view(), name='user_posts'),
    path('by/<username>/<pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('new/post/', views.PostCreateView.as_view(), name='post_create'),
    path('delete/<pk>', views.PostDeleteView.as_view(), name='delete_post'),

    ]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import SignUpView
from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('profile/', include('accounts.urls', namespace='profile')),
    path('', HomeView.as_view(), name='home'),


    path('group/', include('groups.urls', namespace="groups")),
    path('post/', include('posts.urls', namespace="posts")),
    path('search/', include('searches.urls', namespace="search")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/_footer.html
<div class="container2 cyan brackets">
  <a>oza</a>
  <a href="https://github.com/osama-abbasss" target="_blank">GitHub</a>
  <a href="https://www.linkedin.com/in/oabbass/" target="_blank" >ABOUT ME</a>
  <a <a href="mailto:eng.oabbass@gmail.com" target="_blank" >CONTACT</a>
</div>

src/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light " style="background-color:#e3f2fd;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">Groups</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:all_posts' %}">posts</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:post_create' %}">create posts</a>
        </li>
        {% endif %}
      </ul>
      <form class="form-inline my-2 my-lg-0" action="/search/">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='q'>
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user-circle"></i> profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'accounts:profile' request.user.profile.PROSlug %}">profile</a>
              {% endif %}
              <a class="dropdown-item" href="{% url 'groups:all_groups' %}">groups</a>

              {% if user.is_authenticated %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'groups:create_group' %}">create group</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
              <a class="dropdown-item" href="{% url 'logout' %}">logout</a>
              {% else %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'login' %}">login</a>
              <a class="dropdown-item" href="{% url 'signup' %}">signup</a>
              {% endif %}

            </div>
          </li>
        </ul>
      </form>
    </div>
  </div>
</nav>

src/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href='{% static "css/main.css" %}'>
    <title>{% block title %}{% endblock %}</title>
    <title>Dark Social</title>

    {% block extra_links %}{% endblock %}
    <script src="https://kit.fontawesome.com/39f020228e.js" crossorigin="anonymous"></script>

  </head>
  <body>
    {% include "_navbar.html" %}

    {% block content %}{% endblock %}

    {% block extra_scripts %}{% endblock %}

    {% include "_footer.html" %}


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block extra_links %}<link rel="stylesheet" href="{% static 'css/home.css' %}">{% endblock %}


{% block content %}

    <div class="bd-example">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>

            </ol>
            <div class="carousel-inner">

            <div class="carousel-item active">
                <img src="https://live.staticflickr.com/1884/29342747487_cf522519fd_b.jpg" class="d-block w-100" alt="bns">
                <div class="carousel-caption d-none d-md-block">
                <h5>Hello in Simple Social</h5>
                <p>Just create your own group and share your posts</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="https://cdn.pixabay.com/photo/2017/08/17/13/33/business-2651346_960_720.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                <h5>hope you enjoying</h5>
                <p>osama abbas</p>
                </div>
            </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </a>
        </div>

    </div>



    <section class=" cards">

          <div class="card1">

              <img src="https://www.searchpng.com/wp-content/uploads/2019/01/silver-medal-png-715x715.png" class="cardimg cardimg2" alt="">

              <h3>Contact Me</h3>

              <h1><a  href="https://www.linkedin.com/in/oabbass/" target="_blank" class="fab fa-linkedin"></a></h1>

              <h1><a href="https://github.com/osama-abbasss" target="_blank" class="fab fa-github"></a></h1>

              <h1><a href="https://www.facebook.com/Osama.Abbasss" target="_blank" class="fab fa-facebook-f"></a></h1>

              <h1><a href="https://twitter.com/osama_abbasss" target="_blank" class="fab fa-twitter"></a></h1>



          </div>

          <div class="card2">
              <img src="http://www.pngmart.com/files/7/Gold-Medal-PNG-Pic.png"  class="cardimg" alt="">
              <h1>name</h1>
              <h3>osama abbas</h3>

              <h1>Title</h1>
              <h3>Web Develover</h3>

              <h1>Email</h1>
              <h3><a href="mailto:eng.oabbass@gmail.com">eng.oabbass@gmail.com</a></h3>

          </div>

          <div class="card3">
              <img src="https://pngriver.com/wp-content/uploads/2018/04/Download-Bronze-Medal-PNG-Image.png" class="cardimg" alt="">

              <h1>Self Study Courses</h1>
              <h2>Front-end</h2>
              <h3>Html, Css & Css3, BootStrap</h3>
              <h3>JavaScript, Jquery</h3>
              <h2>Back-end</h2>
              <h3>python & Django</h3>


          </div>

    </section>


{% endblock %}