src/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.GroupListView.as_view(), name='all_groups'),
    path('posts/in/<slug>/', views.DetailGroupView.as_view(), name='single_group'),
    path('create/', views.CreateGroup.as_view(), name='create_group'),
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave'),


]

src/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostsList.as_view(), name='all_posts'),
    path('by/<username>/', views.UserPostsList.as_view(), name='user_posts'),
    path('by/<username>/<pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('new/post/', views.PostCreateView.as_view(), name='post_create'),
    path('delete/<pk>', views.PostDeleteView.as_view(), name='delete_post'),

    ]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import SignUpView
from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('profile/', include('accounts.urls', namespace='profile')),
    path('', HomeView.as_view(), name='home'),


    path('group/', include('groups.urls', namespace="groups")),
    path('post/', include('posts.urls', namespace="posts")),
    path('search/', include('searches.urls', namespace="search")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from groups.models import Group
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(Group, related_name='posts', on_delete=models.CASCADE, blank=True, null=True)

    def __Str__(self):
        return self.user.username

    class Meta:
        ordering = ['-created_at', ]
        unique_together = ['user', 'text']

src/posts/views.py
from django.shortcuts import render
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from braces.views import SelectRelatedMixin
from . import models, forms

from django.contrib.auth import get_user_model

User = get_user_model()


class PostsList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

class UserPostsList(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self, *args, **kwargs):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact = self.kwargs.get("username"))
        except User.DoesNotExist:
            return Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(str(self.kwargs['username']))
        context['post_user'] = self.post_user
        return context


class PostDetailView(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact = self.kwargs.get('username'))


class PostCreateView(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    model = models.Post
    fields = ['text', 'group']
    success_url = reverse_lazy('posts:all_posts')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)



class PostDeleteView(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all_posts')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

src/posts/templates/posts/_post.html
<hr>
<div class="media">
  <div class="media-body">
    <h5 class="mt-0 mb-1">{{post.text|safe}}</h5>
    <br>
    <a href="{% url 'groups:single_group' post.group.slug %}"  class="badge badge-secondary"> {{post.group.name}}</a>
    <br>
    <a  href="{% url 'posts:user_posts' post.user.username %}"> {{post.user.username}}  - </a>
    <a href="{% url 'posts:post_detail' post.user.username post.pk %}">{{ post.created_at|date:"d/M/y"|lower }}</a>

  </div>
  {% if user.is_authenticated and post.user == request.user %}
    <a href="{% url 'posts:delete_post' post.pk %}" title="delete" class="btn btn-light ">
      <span class="fas fa-trash-alt text-danger " aria-hidden='true'> </span>
      <span class="text-danger icon-lable">Delete</span>
    </a>
  {% endif %}
</div>
<hr>

src/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block title %}{% block post_title %}{% endblock %}{% endblock %}


{% block content %}
  <div class="posts_page">
   <div class="container mt-3 mb-3">
     <div class="row">

       {% block pre_post %}{% endblock %}
       {% block post %}{% endblock %}
       {% block after_post %}{% endblock %}

     </div>
   </div>
  </div>
{% endblock %}

src/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}
{% block post_title %} Delete Post {% endblock %}


{% block post %}


<form method="post">
  <h3>Are you sure you want delete this post </h3>
  {% csrf_token %}
  <br>
  <hr>
  <button type="submit" class="btn btn-danger"> Delete</button>
  <a href="{% url 'posts:post_detail' post.user.username post.pk %}" class="btn btn-primary">cancel</a>
</form>

{% endblock %}

src/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% block post_title %} Post detail {% endblock %}

{% block post %}
<div class="col-md-8">
  {% include "posts/_post.html" %}
</div>
{% endblock %}

src/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load crispy_forms_tags %}
{% block post_title %} create post{% endblock %}


{% block post %}
<form  method="post"  action="{% url 'posts:post_create' %}">
  <h2> Create New post!</h2>
  {% csrf_token %}
  {{ form|crispy }}
    <button type="submit" class="btn btn-primary">post</button>
</form>

{% endblock %}

src/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% block post_title %} Post List {% endblock %}

{% block pre_post %}
  <div class="col-md-4">
    {% if user.is_authenticated %}
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">your Groups</h5>
        </div>
        <ul class="list-group list-group-flush">
          {% for user_group in object_list %}
            {% if user_group.user in user_group.group.members.all %}
              <li class="list-group-item">
                <a class="btn btn-light btn-lg btn-block" href="{% url 'groups:single_group' user_group.group.slug %}">{{user_group.group.name}}</a>
              </li>

            {% endif %}
          {% endfor %}
        </ul>
      </div>
    {% endif %}
  </div>
  <div class="col-md-4">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">all Groups</h5>
      </div>
      <ul class="list-group list-group-flush">
        {% for all_group in object_list %}

          <li class="list-group-item">
            <a class="btn btn-info btn-lg btn-block" href="{% url 'groups:single_group' all_group.group.slug %}">{{all_group.group.name}}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
<br>
{% endblock %}


{% block post %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
  </div>
{% endblock %}

src/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}
{% block post_title %} dark group {% endblock %}

{% block post %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
  </div>
{% endblock %}